// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: budget.sql

package db

import (
	"context"
)

const createBudget = `-- name: CreateBudget :one
INSERT INTO budgets (
  owner,
  category_id,
  monthly_limit,
  month,
  year
) VALUES (
  $1, $2, $3, $4, $5
) RETURNING id, owner, category_id, monthly_limit, month, year, created_at
`

type CreateBudgetParams struct {
	Owner        string `json:"owner"`
	CategoryID   int64  `json:"category_id"`
	MonthlyLimit int64  `json:"monthly_limit"`
	Month        int32  `json:"month"`
	Year         int32  `json:"year"`
}

func (q *Queries) CreateBudget(ctx context.Context, arg CreateBudgetParams) (Budget, error) {
	row := q.db.QueryRow(ctx, createBudget,
		arg.Owner,
		arg.CategoryID,
		arg.MonthlyLimit,
		arg.Month,
		arg.Year,
	)
	var i Budget
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.CategoryID,
		&i.MonthlyLimit,
		&i.Month,
		&i.Year,
		&i.CreatedAt,
	)
	return i, err
}

const deleteBudget = `-- name: DeleteBudget :exec
DELETE FROM budgets
WHERE id = $1
`

func (q *Queries) DeleteBudget(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteBudget, id)
	return err
}

const getBudget = `-- name: GetBudget :one
SELECT id, owner, category_id, monthly_limit, month, year, created_at FROM budgets
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetBudget(ctx context.Context, id int64) (Budget, error) {
	row := q.db.QueryRow(ctx, getBudget, id)
	var i Budget
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.CategoryID,
		&i.MonthlyLimit,
		&i.Month,
		&i.Year,
		&i.CreatedAt,
	)
	return i, err
}

const getBudgetByCategoryAndMonth = `-- name: GetBudgetByCategoryAndMonth :one
SELECT id, owner, category_id, monthly_limit, month, year, created_at FROM budgets
WHERE owner = $1
  AND category_id = $2
  AND month = $3
  AND year = $4
LIMIT 1
`

type GetBudgetByCategoryAndMonthParams struct {
	Owner      string `json:"owner"`
	CategoryID int64  `json:"category_id"`
	Month      int32  `json:"month"`
	Year       int32  `json:"year"`
}

func (q *Queries) GetBudgetByCategoryAndMonth(ctx context.Context, arg GetBudgetByCategoryAndMonthParams) (Budget, error) {
	row := q.db.QueryRow(ctx, getBudgetByCategoryAndMonth,
		arg.Owner,
		arg.CategoryID,
		arg.Month,
		arg.Year,
	)
	var i Budget
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.CategoryID,
		&i.MonthlyLimit,
		&i.Month,
		&i.Year,
		&i.CreatedAt,
	)
	return i, err
}

const listBudgets = `-- name: ListBudgets :many
SELECT id, owner, category_id, monthly_limit, month, year, created_at FROM budgets
WHERE owner = $1
  AND month = $2
  AND year = $3
ORDER BY id
`

type ListBudgetsParams struct {
	Owner string `json:"owner"`
	Month int32  `json:"month"`
	Year  int32  `json:"year"`
}

func (q *Queries) ListBudgets(ctx context.Context, arg ListBudgetsParams) ([]Budget, error) {
	rows, err := q.db.Query(ctx, listBudgets, arg.Owner, arg.Month, arg.Year)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Budget{}
	for rows.Next() {
		var i Budget
		if err := rows.Scan(
			&i.ID,
			&i.Owner,
			&i.CategoryID,
			&i.MonthlyLimit,
			&i.Month,
			&i.Year,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBudget = `-- name: UpdateBudget :one
UPDATE budgets
SET monthly_limit = $2
WHERE id = $1
RETURNING id, owner, category_id, monthly_limit, month, year, created_at
`

type UpdateBudgetParams struct {
	ID           int64 `json:"id"`
	MonthlyLimit int64 `json:"monthly_limit"`
}

func (q *Queries) UpdateBudget(ctx context.Context, arg UpdateBudgetParams) (Budget, error) {
	row := q.db.QueryRow(ctx, updateBudget, arg.ID, arg.MonthlyLimit)
	var i Budget
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.CategoryID,
		&i.MonthlyLimit,
		&i.Month,
		&i.Year,
		&i.CreatedAt,
	)
	return i, err
}
