// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: category.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (
  owner,
  name,
  type
) VALUES (
  $1, $2, $3
) RETURNING id, owner, name, type, created_at
`

type CreateCategoryParams struct {
	Owner pgtype.Text `json:"owner"`
	Name  string      `json:"name"`
	Type  string      `json:"type"`
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, createCategory,
		arg.Owner,
		arg.Name,
		arg.Type,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Name,
		&i.Type,
		&i.CreatedAt,
	)
	return i, err
}

const deleteCategory = `-- name: DeleteCategory :exec
DELETE FROM categories
WHERE id = $1
`

func (q *Queries) DeleteCategory(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteCategory, id)
	return err
}

const getCategory = `-- name: GetCategory :one
SELECT id, owner, name, type, created_at FROM categories
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetCategory(ctx context.Context, id int64) (Category, error) {
	row := q.db.QueryRow(ctx, getCategory, id)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Name,
		&i.Type,
		&i.CreatedAt,
	)
	return i, err
}

const listCategories = `-- name: ListCategories :many
SELECT id, owner, name, type, created_at FROM categories
WHERE owner IS NULL OR owner = $1
ORDER BY name
`

func (q *Queries) ListCategories(ctx context.Context, owner string) ([]Category, error) {
	rows, err := q.db.Query(ctx, listCategories, owner)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Owner,
			&i.Name,
			&i.Type,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategoriesByType = `-- name: ListCategoriesByType :many
SELECT id, owner, name, type, created_at FROM categories
WHERE (owner IS NULL OR owner = $1) AND type = $2
ORDER BY name
`

type ListCategoriesByTypeParams struct {
	Owner string `json:"owner"`
	Type  string `json:"type"`
}

func (q *Queries) ListCategoriesByType(ctx context.Context, arg ListCategoriesByTypeParams) ([]Category, error) {
	rows, err := q.db.Query(ctx, listCategoriesByType, arg.Owner, arg.Type)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Owner,
			&i.Name,
			&i.Type,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
