// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: entry.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEntry = `-- name: CreateEntry :one
INSERT INTO entries (
  account_id,
  category_id,
  amount,
  note
) VALUES (
  $1, $2, $3, $4
) RETURNING id, account_id, category_id, amount, note, created_at
`

type CreateEntryParams struct {
	AccountID  int64       `json:"account_id"`
	CategoryID pgtype.Int8 `json:"category_id"`
	Amount     int64       `json:"amount"`
	Note       pgtype.Text `json:"note"`
}

func (q *Queries) CreateEntry(ctx context.Context, arg CreateEntryParams) (Entry, error) {
	row := q.db.QueryRow(ctx, createEntry,
		arg.AccountID,
		arg.CategoryID,
		arg.Amount,
		arg.Note,
	)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.CategoryID,
		&i.Amount,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}

const getEntry = `-- name: GetEntry :one
SELECT id, account_id, category_id, amount, note, created_at FROM entries
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetEntry(ctx context.Context, id int64) (Entry, error) {
	row := q.db.QueryRow(ctx, getEntry, id)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.CategoryID,
		&i.Amount,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}

const listEntries = `-- name: ListEntries :many
SELECT id, account_id, category_id, amount, note, created_at FROM entries
WHERE account_id = $1
ORDER BY created_at DESC
LIMIT $2
OFFSET $3
`

type ListEntriesParams struct {
	AccountID int64 `json:"account_id"`
	Limit     int32 `json:"limit"`
	Offset    int32 `json:"offset"`
}

func (q *Queries) ListEntries(ctx context.Context, arg ListEntriesParams) ([]Entry, error) {
	rows, err := q.db.Query(ctx, listEntries, arg.AccountID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Entry{}
	for rows.Next() {
		var i Entry
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.CategoryID,
			&i.Amount,
			&i.Note,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntriesByCategory = `-- name: ListEntriesByCategory :many
SELECT id, account_id, category_id, amount, note, created_at FROM entries
WHERE account_id = $1 AND category_id = $2
ORDER BY created_at DESC
LIMIT $3
OFFSET $4
`

type ListEntriesByCategoryParams struct {
	AccountID  int64       `json:"account_id"`
	CategoryID pgtype.Int8 `json:"category_id"`
	Limit      int32       `json:"limit"`
	Offset     int32       `json:"offset"`
}

func (q *Queries) ListEntriesByCategory(ctx context.Context, arg ListEntriesByCategoryParams) ([]Entry, error) {
	rows, err := q.db.Query(ctx, listEntriesByCategory,
		arg.AccountID,
		arg.CategoryID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Entry{}
	for rows.Next() {
		var i Entry
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.CategoryID,
			&i.Amount,
			&i.Note,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAccountSummary = `-- name: GetAccountSummary :one
SELECT
  COALESCE(SUM(amount) FILTER (WHERE amount > 0), 0)::bigint AS total_income,
  COALESCE(SUM(amount) FILTER (WHERE amount < 0), 0)::bigint AS total_expense,
  COALESCE(SUM(amount), 0)::bigint AS net_balance
FROM entries
WHERE account_id = $1
  AND created_at >= $2
  AND created_at < $3
`

type GetAccountSummaryParams struct {
	AccountID int64     `json:"account_id"`
	FromTime  time.Time `json:"from_time"`
	ToTime    time.Time `json:"to_time"`
}

type GetAccountSummaryRow struct {
	TotalIncome  int64 `json:"total_income"`
	TotalExpense int64 `json:"total_expense"`
	NetBalance   int64 `json:"net_balance"`
}

func (q *Queries) GetAccountSummary(ctx context.Context, arg GetAccountSummaryParams) (GetAccountSummaryRow, error) {
	row := q.db.QueryRow(ctx, getAccountSummary, arg.AccountID, arg.FromTime, arg.ToTime)
	var i GetAccountSummaryRow
	err := row.Scan(
		&i.TotalIncome,
		&i.TotalExpense,
		&i.NetBalance,
	)
	return i, err
}
