// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID                int64     `json:"id"`
	Username          string    `json:"username"`
	HashedPassword    string    `json:"hashed_password"`
	FullName          string    `json:"full_name"`
	Email             string    `json:"email"`
	PasswordChangedAt time.Time `json:"password_changed_at"`
	CreatedAt         time.Time `json:"created_at"`
}

type Account struct {
	ID        int64     `json:"id"`
	Owner     string    `json:"owner"`
	Name      string    `json:"name"`
	Balance   int64     `json:"balance"`
	Currency  string    `json:"currency"`
	CreatedAt time.Time `json:"created_at"`
}

type Category struct {
	ID        int64       `json:"id"`
	Owner     pgtype.Text `json:"owner"`
	Name      string      `json:"name"`
	Type      string      `json:"type"`
	CreatedAt time.Time   `json:"created_at"`
}

type Entry struct {
	ID         int64       `json:"id"`
	AccountID  int64       `json:"account_id"`
	CategoryID pgtype.Int8 `json:"category_id"`
	Amount     int64       `json:"amount"`
	Note       pgtype.Text `json:"note"`
	CreatedAt  time.Time   `json:"created_at"`
}

type Transfer struct {
	ID            int64     `json:"id"`
	FromAccountID int64     `json:"from_account_id"`
	ToAccountID   int64     `json:"to_account_id"`
	Amount        int64     `json:"amount"`
	CreatedAt     time.Time `json:"created_at"`
}

type Budget struct {
	ID           int64     `json:"id"`
	Owner        string    `json:"owner"`
	CategoryID   int64     `json:"category_id"`
	MonthlyLimit int64     `json:"monthly_limit"`
	Month        int32     `json:"month"`
	Year         int32     `json:"year"`
	CreatedAt    time.Time `json:"created_at"`
}

type SavingsGoal struct {
	ID              int64       `json:"id"`
	Owner           string      `json:"owner"`
	Title           string      `json:"title"`
	TargetAmount    int64       `json:"target_amount"`
	CurrentAmount   int64       `json:"current_amount"`
	TargetDate      pgtype.Date `json:"target_date"`
	LinkedAccountID int64       `json:"linked_account_id"`
	CreatedAt       time.Time   `json:"created_at"`
}

type RecurringPayment struct {
	ID          int64     `json:"id"`
	Owner       string    `json:"owner"`
	Title       string    `json:"title"`
	Amount      int64     `json:"amount"`
	CategoryID  int64     `json:"category_id"`
	Frequency   string    `json:"frequency"`
	NextDueDate time.Time `json:"next_due_date"`
	CreatedAt   time.Time `json:"created_at"`
}
