// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// User queries
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetUser(ctx context.Context, username string) (User, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)

	// Account queries
	AddAccountBalance(ctx context.Context, arg AddAccountBalanceParams) (Account, error)
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	DeleteAccount(ctx context.Context, id int64) error
	GetAccount(ctx context.Context, id int64) (Account, error)
	GetAccountForUpdate(ctx context.Context, id int64) (Account, error)
	ListAccounts(ctx context.Context, arg ListAccountsParams) ([]Account, error)
	UpdateAccount(ctx context.Context, arg UpdateAccountParams) (Account, error)

	// Entry queries
	CreateEntry(ctx context.Context, arg CreateEntryParams) (Entry, error)
	GetAccountSummary(ctx context.Context, arg GetAccountSummaryParams) (GetAccountSummaryRow, error)
	GetEntry(ctx context.Context, id int64) (Entry, error)
	ListEntries(ctx context.Context, arg ListEntriesParams) ([]Entry, error)
	ListEntriesByCategory(ctx context.Context, arg ListEntriesByCategoryParams) ([]Entry, error)

	// Transfer queries
	CreateTransfer(ctx context.Context, arg CreateTransferParams) (Transfer, error)
	GetTransfer(ctx context.Context, id int64) (Transfer, error)
	ListTransfers(ctx context.Context, arg ListTransfersParams) ([]Transfer, error)

	// Category queries
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error)
	DeleteCategory(ctx context.Context, id int64) error
	GetCategory(ctx context.Context, id int64) (Category, error)
	ListCategories(ctx context.Context, owner string) ([]Category, error)
	ListCategoriesByType(ctx context.Context, arg ListCategoriesByTypeParams) ([]Category, error)

	// Budget queries
	CreateBudget(ctx context.Context, arg CreateBudgetParams) (Budget, error)
	DeleteBudget(ctx context.Context, id int64) error
	GetBudget(ctx context.Context, id int64) (Budget, error)
	GetBudgetByCategoryAndMonth(ctx context.Context, arg GetBudgetByCategoryAndMonthParams) (Budget, error)
	ListBudgets(ctx context.Context, arg ListBudgetsParams) ([]Budget, error)
	UpdateBudget(ctx context.Context, arg UpdateBudgetParams) (Budget, error)

	// Savings goal queries
	AddToSavingsGoal(ctx context.Context, arg AddToSavingsGoalParams) (SavingsGoal, error)
	CreateSavingsGoal(ctx context.Context, arg CreateSavingsGoalParams) (SavingsGoal, error)
	DeleteSavingsGoal(ctx context.Context, id int64) error
	GetSavingsGoal(ctx context.Context, id int64) (SavingsGoal, error)
	ListSavingsGoals(ctx context.Context, owner string) ([]SavingsGoal, error)

	// Recurring payment queries
	CreateRecurringPayment(ctx context.Context, arg CreateRecurringPaymentParams) (RecurringPayment, error)
	DeleteRecurringPayment(ctx context.Context, id int64) error
	GetRecurringPayment(ctx context.Context, id int64) (RecurringPayment, error)
	ListDueRecurringPayments(ctx context.Context, arg ListDueRecurringPaymentsParams) ([]RecurringPayment, error)
	ListRecurringPayments(ctx context.Context, owner string) ([]RecurringPayment, error)
	UpdateRecurringPaymentDueDate(ctx context.Context, arg UpdateRecurringPaymentDueDateParams) (RecurringPayment, error)
}

// Ensure Queries implements Querier at compile time.
var _ Querier = (*Queries)(nil)

// unused import guard
var _ = time.Now
var _ pgtype.Text
