// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: recurring_payment.sql

package db

import (
	"context"
	"time"
)

const createRecurringPayment = `-- name: CreateRecurringPayment :one
INSERT INTO recurring_payments (
  owner,
  title,
  amount,
  category_id,
  frequency,
  next_due_date
) VALUES (
  $1, $2, $3, $4, $5, $6
) RETURNING id, owner, title, amount, category_id, frequency, next_due_date, created_at
`

type CreateRecurringPaymentParams struct {
	Owner       string    `json:"owner"`
	Title       string    `json:"title"`
	Amount      int64     `json:"amount"`
	CategoryID  int64     `json:"category_id"`
	Frequency   string    `json:"frequency"`
	NextDueDate time.Time `json:"next_due_date"`
}

func (q *Queries) CreateRecurringPayment(ctx context.Context, arg CreateRecurringPaymentParams) (RecurringPayment, error) {
	row := q.db.QueryRow(ctx, createRecurringPayment,
		arg.Owner,
		arg.Title,
		arg.Amount,
		arg.CategoryID,
		arg.Frequency,
		arg.NextDueDate,
	)
	var i RecurringPayment
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Title,
		&i.Amount,
		&i.CategoryID,
		&i.Frequency,
		&i.NextDueDate,
		&i.CreatedAt,
	)
	return i, err
}

const deleteRecurringPayment = `-- name: DeleteRecurringPayment :exec
DELETE FROM recurring_payments
WHERE id = $1
`

func (q *Queries) DeleteRecurringPayment(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteRecurringPayment, id)
	return err
}

const getRecurringPayment = `-- name: GetRecurringPayment :one
SELECT id, owner, title, amount, category_id, frequency, next_due_date, created_at FROM recurring_payments
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetRecurringPayment(ctx context.Context, id int64) (RecurringPayment, error) {
	row := q.db.QueryRow(ctx, getRecurringPayment, id)
	var i RecurringPayment
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Title,
		&i.Amount,
		&i.CategoryID,
		&i.Frequency,
		&i.NextDueDate,
		&i.CreatedAt,
	)
	return i, err
}

const listRecurringPayments = `-- name: ListRecurringPayments :many
SELECT id, owner, title, amount, category_id, frequency, next_due_date, created_at FROM recurring_payments
WHERE owner = $1
ORDER BY next_due_date ASC
`

func (q *Queries) ListRecurringPayments(ctx context.Context, owner string) ([]RecurringPayment, error) {
	rows, err := q.db.Query(ctx, listRecurringPayments, owner)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecurringPayment{}
	for rows.Next() {
		var i RecurringPayment
		if err := rows.Scan(
			&i.ID,
			&i.Owner,
			&i.Title,
			&i.Amount,
			&i.CategoryID,
			&i.Frequency,
			&i.NextDueDate,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDueRecurringPayments = `-- name: ListDueRecurringPayments :many
SELECT id, owner, title, amount, category_id, frequency, next_due_date, created_at FROM recurring_payments
WHERE owner = $1
  AND next_due_date <= $2
ORDER BY next_due_date ASC
`

type ListDueRecurringPaymentsParams struct {
	Owner       string    `json:"owner"`
	NextDueDate time.Time `json:"next_due_date"`
}

func (q *Queries) ListDueRecurringPayments(ctx context.Context, arg ListDueRecurringPaymentsParams) ([]RecurringPayment, error) {
	rows, err := q.db.Query(ctx, listDueRecurringPayments, arg.Owner, arg.NextDueDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecurringPayment{}
	for rows.Next() {
		var i RecurringPayment
		if err := rows.Scan(
			&i.ID,
			&i.Owner,
			&i.Title,
			&i.Amount,
			&i.CategoryID,
			&i.Frequency,
			&i.NextDueDate,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRecurringPaymentDueDate = `-- name: UpdateRecurringPaymentDueDate :one
UPDATE recurring_payments
SET next_due_date = $2
WHERE id = $1
RETURNING id, owner, title, amount, category_id, frequency, next_due_date, created_at
`

type UpdateRecurringPaymentDueDateParams struct {
	ID          int64     `json:"id"`
	NextDueDate time.Time `json:"next_due_date"`
}

func (q *Queries) UpdateRecurringPaymentDueDate(ctx context.Context, arg UpdateRecurringPaymentDueDateParams) (RecurringPayment, error) {
	row := q.db.QueryRow(ctx, updateRecurringPaymentDueDate, arg.ID, arg.NextDueDate)
	var i RecurringPayment
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Title,
		&i.Amount,
		&i.CategoryID,
		&i.Frequency,
		&i.NextDueDate,
		&i.CreatedAt,
	)
	return i, err
}
