// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: savings_goal.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addToSavingsGoal = `-- name: AddToSavingsGoal :one
UPDATE savings_goals
SET current_amount = current_amount + $1
WHERE id = $2
RETURNING id, owner, title, target_amount, current_amount, target_date, linked_account_id, created_at
`

type AddToSavingsGoalParams struct {
	Amount int64 `json:"amount"`
	ID     int64 `json:"id"`
}

func (q *Queries) AddToSavingsGoal(ctx context.Context, arg AddToSavingsGoalParams) (SavingsGoal, error) {
	row := q.db.QueryRow(ctx, addToSavingsGoal, arg.Amount, arg.ID)
	var i SavingsGoal
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Title,
		&i.TargetAmount,
		&i.CurrentAmount,
		&i.TargetDate,
		&i.LinkedAccountID,
		&i.CreatedAt,
	)
	return i, err
}

const createSavingsGoal = `-- name: CreateSavingsGoal :one
INSERT INTO savings_goals (
  owner,
  title,
  target_amount,
  current_amount,
  target_date,
  linked_account_id
) VALUES (
  $1, $2, $3, $4, $5, $6
) RETURNING id, owner, title, target_amount, current_amount, target_date, linked_account_id, created_at
`

type CreateSavingsGoalParams struct {
	Owner           string      `json:"owner"`
	Title           string      `json:"title"`
	TargetAmount    int64       `json:"target_amount"`
	CurrentAmount   int64       `json:"current_amount"`
	TargetDate      pgtype.Date `json:"target_date"`
	LinkedAccountID int64       `json:"linked_account_id"`
}

func (q *Queries) CreateSavingsGoal(ctx context.Context, arg CreateSavingsGoalParams) (SavingsGoal, error) {
	row := q.db.QueryRow(ctx, createSavingsGoal,
		arg.Owner,
		arg.Title,
		arg.TargetAmount,
		arg.CurrentAmount,
		arg.TargetDate,
		arg.LinkedAccountID,
	)
	var i SavingsGoal
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Title,
		&i.TargetAmount,
		&i.CurrentAmount,
		&i.TargetDate,
		&i.LinkedAccountID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteSavingsGoal = `-- name: DeleteSavingsGoal :exec
DELETE FROM savings_goals
WHERE id = $1
`

func (q *Queries) DeleteSavingsGoal(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteSavingsGoal, id)
	return err
}

const getSavingsGoal = `-- name: GetSavingsGoal :one
SELECT id, owner, title, target_amount, current_amount, target_date, linked_account_id, created_at FROM savings_goals
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetSavingsGoal(ctx context.Context, id int64) (SavingsGoal, error) {
	row := q.db.QueryRow(ctx, getSavingsGoal, id)
	var i SavingsGoal
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Title,
		&i.TargetAmount,
		&i.CurrentAmount,
		&i.TargetDate,
		&i.LinkedAccountID,
		&i.CreatedAt,
	)
	return i, err
}

const listSavingsGoals = `-- name: ListSavingsGoals :many
SELECT id, owner, title, target_amount, current_amount, target_date, linked_account_id, created_at FROM savings_goals
WHERE owner = $1
ORDER BY created_at DESC
`

func (q *Queries) ListSavingsGoals(ctx context.Context, owner string) ([]SavingsGoal, error) {
	rows, err := q.db.Query(ctx, listSavingsGoals, owner)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SavingsGoal{}
	for rows.Next() {
		var i SavingsGoal
		if err := rows.Scan(
			&i.ID,
			&i.Owner,
			&i.Title,
			&i.TargetAmount,
			&i.CurrentAmount,
			&i.TargetDate,
			&i.LinkedAccountID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
