// Code generated by MockGen. DO NOT EDIT.
// Run `make mock` to regenerate after changing the Store interface.

package mockdb

import (
	"context"
	"reflect"
	"time"

	db "github.com/shresth/ledgr/db/sqlc"
	gomock "go.uber.org/mock/gomock"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// ── User ─────────────────────────────────────────────────────────────────────

func (m *MockStore) CreateUser(ctx context.Context, arg db.CreateUserParams) (db.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, arg)
	return ret[0].(db.User), mockErr(ret[1])
}
func (r *MockStoreMockRecorder) CreateUser(ctx, arg interface{}) *gomock.Call {
	return r.mock.ctrl.RecordCallWithMethodType(r.mock, "CreateUser", reflect.TypeOf((*MockStore)(nil).CreateUser), ctx, arg)
}

func (m *MockStore) GetUser(ctx context.Context, username string) (db.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUser", ctx, username)
	return ret[0].(db.User), mockErr(ret[1])
}
func (r *MockStoreMockRecorder) GetUser(ctx, username interface{}) *gomock.Call {
	return r.mock.ctrl.RecordCallWithMethodType(r.mock, "GetUser", reflect.TypeOf((*MockStore)(nil).GetUser), ctx, username)
}

func (m *MockStore) UpdateUser(ctx context.Context, arg db.UpdateUserParams) (db.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUser", ctx, arg)
	return ret[0].(db.User), mockErr(ret[1])
}
func (r *MockStoreMockRecorder) UpdateUser(ctx, arg interface{}) *gomock.Call {
	return r.mock.ctrl.RecordCallWithMethodType(r.mock, "UpdateUser", reflect.TypeOf((*MockStore)(nil).UpdateUser), ctx, arg)
}

// ── Account ───────────────────────────────────────────────────────────────────

func (m *MockStore) CreateAccount(ctx context.Context, arg db.CreateAccountParams) (db.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAccount", ctx, arg)
	return ret[0].(db.Account), mockErr(ret[1])
}
func (r *MockStoreMockRecorder) CreateAccount(ctx, arg interface{}) *gomock.Call {
	return r.mock.ctrl.RecordCallWithMethodType(r.mock, "CreateAccount", reflect.TypeOf((*MockStore)(nil).CreateAccount), ctx, arg)
}

func (m *MockStore) GetAccount(ctx context.Context, id int64) (db.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccount", ctx, id)
	return ret[0].(db.Account), mockErr(ret[1])
}
func (r *MockStoreMockRecorder) GetAccount(ctx, id interface{}) *gomock.Call {
	return r.mock.ctrl.RecordCallWithMethodType(r.mock, "GetAccount", reflect.TypeOf((*MockStore)(nil).GetAccount), ctx, id)
}

func (m *MockStore) GetAccountForUpdate(ctx context.Context, id int64) (db.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccountForUpdate", ctx, id)
	return ret[0].(db.Account), mockErr(ret[1])
}
func (r *MockStoreMockRecorder) GetAccountForUpdate(ctx, id interface{}) *gomock.Call {
	return r.mock.ctrl.RecordCallWithMethodType(r.mock, "GetAccountForUpdate", reflect.TypeOf((*MockStore)(nil).GetAccountForUpdate), ctx, id)
}

func (m *MockStore) ListAccounts(ctx context.Context, arg db.ListAccountsParams) ([]db.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAccounts", ctx, arg)
	return ret[0].([]db.Account), mockErr(ret[1])
}
func (r *MockStoreMockRecorder) ListAccounts(ctx, arg interface{}) *gomock.Call {
	return r.mock.ctrl.RecordCallWithMethodType(r.mock, "ListAccounts", reflect.TypeOf((*MockStore)(nil).ListAccounts), ctx, arg)
}

func (m *MockStore) UpdateAccount(ctx context.Context, arg db.UpdateAccountParams) (db.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAccount", ctx, arg)
	return ret[0].(db.Account), mockErr(ret[1])
}
func (r *MockStoreMockRecorder) UpdateAccount(ctx, arg interface{}) *gomock.Call {
	return r.mock.ctrl.RecordCallWithMethodType(r.mock, "UpdateAccount", reflect.TypeOf((*MockStore)(nil).UpdateAccount), ctx, arg)
}

func (m *MockStore) AddAccountBalance(ctx context.Context, arg db.AddAccountBalanceParams) (db.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddAccountBalance", ctx, arg)
	return ret[0].(db.Account), mockErr(ret[1])
}
func (r *MockStoreMockRecorder) AddAccountBalance(ctx, arg interface{}) *gomock.Call {
	return r.mock.ctrl.RecordCallWithMethodType(r.mock, "AddAccountBalance", reflect.TypeOf((*MockStore)(nil).AddAccountBalance), ctx, arg)
}

func (m *MockStore) DeleteAccount(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAccount", ctx, id)
	return mockErr(ret[0])
}
func (r *MockStoreMockRecorder) DeleteAccount(ctx, id interface{}) *gomock.Call {
	return r.mock.ctrl.RecordCallWithMethodType(r.mock, "DeleteAccount", reflect.TypeOf((*MockStore)(nil).DeleteAccount), ctx, id)
}

// ── Entry ─────────────────────────────────────────────────────────────────────

func (m *MockStore) CreateEntry(ctx context.Context, arg db.CreateEntryParams) (db.Entry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateEntry", ctx, arg)
	return ret[0].(db.Entry), mockErr(ret[1])
}
func (r *MockStoreMockRecorder) CreateEntry(ctx, arg interface{}) *gomock.Call {
	return r.mock.ctrl.RecordCallWithMethodType(r.mock, "CreateEntry", reflect.TypeOf((*MockStore)(nil).CreateEntry), ctx, arg)
}

func (m *MockStore) GetEntry(ctx context.Context, id int64) (db.Entry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEntry", ctx, id)
	return ret[0].(db.Entry), mockErr(ret[1])
}
func (r *MockStoreMockRecorder) GetEntry(ctx, id interface{}) *gomock.Call {
	return r.mock.ctrl.RecordCallWithMethodType(r.mock, "GetEntry", reflect.TypeOf((*MockStore)(nil).GetEntry), ctx, id)
}

func (m *MockStore) ListEntries(ctx context.Context, arg db.ListEntriesParams) ([]db.Entry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEntries", ctx, arg)
	return ret[0].([]db.Entry), mockErr(ret[1])
}
func (r *MockStoreMockRecorder) ListEntries(ctx, arg interface{}) *gomock.Call {
	return r.mock.ctrl.RecordCallWithMethodType(r.mock, "ListEntries", reflect.TypeOf((*MockStore)(nil).ListEntries), ctx, arg)
}

func (m *MockStore) ListEntriesByCategory(ctx context.Context, arg db.ListEntriesByCategoryParams) ([]db.Entry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEntriesByCategory", ctx, arg)
	return ret[0].([]db.Entry), mockErr(ret[1])
}
func (r *MockStoreMockRecorder) ListEntriesByCategory(ctx, arg interface{}) *gomock.Call {
	return r.mock.ctrl.RecordCallWithMethodType(r.mock, "ListEntriesByCategory", reflect.TypeOf((*MockStore)(nil).ListEntriesByCategory), ctx, arg)
}

func (m *MockStore) GetAccountSummary(ctx context.Context, arg db.GetAccountSummaryParams) (db.GetAccountSummaryRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccountSummary", ctx, arg)
	return ret[0].(db.GetAccountSummaryRow), mockErr(ret[1])
}
func (r *MockStoreMockRecorder) GetAccountSummary(ctx, arg interface{}) *gomock.Call {
	return r.mock.ctrl.RecordCallWithMethodType(r.mock, "GetAccountSummary", reflect.TypeOf((*MockStore)(nil).GetAccountSummary), ctx, arg)
}

// ── Transfer ──────────────────────────────────────────────────────────────────

func (m *MockStore) CreateTransfer(ctx context.Context, arg db.CreateTransferParams) (db.Transfer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTransfer", ctx, arg)
	return ret[0].(db.Transfer), mockErr(ret[1])
}
func (r *MockStoreMockRecorder) CreateTransfer(ctx, arg interface{}) *gomock.Call {
	return r.mock.ctrl.RecordCallWithMethodType(r.mock, "CreateTransfer", reflect.TypeOf((*MockStore)(nil).CreateTransfer), ctx, arg)
}

func (m *MockStore) GetTransfer(ctx context.Context, id int64) (db.Transfer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTransfer", ctx, id)
	return ret[0].(db.Transfer), mockErr(ret[1])
}
func (r *MockStoreMockRecorder) GetTransfer(ctx, id interface{}) *gomock.Call {
	return r.mock.ctrl.RecordCallWithMethodType(r.mock, "GetTransfer", reflect.TypeOf((*MockStore)(nil).GetTransfer), ctx, id)
}

func (m *MockStore) ListTransfers(ctx context.Context, arg db.ListTransfersParams) ([]db.Transfer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTransfers", ctx, arg)
	return ret[0].([]db.Transfer), mockErr(ret[1])
}
func (r *MockStoreMockRecorder) ListTransfers(ctx, arg interface{}) *gomock.Call {
	return r.mock.ctrl.RecordCallWithMethodType(r.mock, "ListTransfers", reflect.TypeOf((*MockStore)(nil).ListTransfers), ctx, arg)
}

// ── Category ──────────────────────────────────────────────────────────────────

func (m *MockStore) CreateCategory(ctx context.Context, arg db.CreateCategoryParams) (db.Category, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCategory", ctx, arg)
	return ret[0].(db.Category), mockErr(ret[1])
}
func (r *MockStoreMockRecorder) CreateCategory(ctx, arg interface{}) *gomock.Call {
	return r.mock.ctrl.RecordCallWithMethodType(r.mock, "CreateCategory", reflect.TypeOf((*MockStore)(nil).CreateCategory), ctx, arg)
}

func (m *MockStore) GetCategory(ctx context.Context, id int64) (db.Category, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCategory", ctx, id)
	return ret[0].(db.Category), mockErr(ret[1])
}
func (r *MockStoreMockRecorder) GetCategory(ctx, id interface{}) *gomock.Call {
	return r.mock.ctrl.RecordCallWithMethodType(r.mock, "GetCategory", reflect.TypeOf((*MockStore)(nil).GetCategory), ctx, id)
}

func (m *MockStore) ListCategories(ctx context.Context, owner string) ([]db.Category, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCategories", ctx, owner)
	return ret[0].([]db.Category), mockErr(ret[1])
}
func (r *MockStoreMockRecorder) ListCategories(ctx, owner interface{}) *gomock.Call {
	return r.mock.ctrl.RecordCallWithMethodType(r.mock, "ListCategories", reflect.TypeOf((*MockStore)(nil).ListCategories), ctx, owner)
}

func (m *MockStore) ListCategoriesByType(ctx context.Context, arg db.ListCategoriesByTypeParams) ([]db.Category, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCategoriesByType", ctx, arg)
	return ret[0].([]db.Category), mockErr(ret[1])
}
func (r *MockStoreMockRecorder) ListCategoriesByType(ctx, arg interface{}) *gomock.Call {
	return r.mock.ctrl.RecordCallWithMethodType(r.mock, "ListCategoriesByType", reflect.TypeOf((*MockStore)(nil).ListCategoriesByType), ctx, arg)
}

func (m *MockStore) DeleteCategory(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCategory", ctx, id)
	return mockErr(ret[0])
}
func (r *MockStoreMockRecorder) DeleteCategory(ctx, id interface{}) *gomock.Call {
	return r.mock.ctrl.RecordCallWithMethodType(r.mock, "DeleteCategory", reflect.TypeOf((*MockStore)(nil).DeleteCategory), ctx, id)
}

// ── Budget ────────────────────────────────────────────────────────────────────

func (m *MockStore) CreateBudget(ctx context.Context, arg db.CreateBudgetParams) (db.Budget, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBudget", ctx, arg)
	return ret[0].(db.Budget), mockErr(ret[1])
}
func (r *MockStoreMockRecorder) CreateBudget(ctx, arg interface{}) *gomock.Call {
	return r.mock.ctrl.RecordCallWithMethodType(r.mock, "CreateBudget", reflect.TypeOf((*MockStore)(nil).CreateBudget), ctx, arg)
}

func (m *MockStore) GetBudget(ctx context.Context, id int64) (db.Budget, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBudget", ctx, id)
	return ret[0].(db.Budget), mockErr(ret[1])
}
func (r *MockStoreMockRecorder) GetBudget(ctx, id interface{}) *gomock.Call {
	return r.mock.ctrl.RecordCallWithMethodType(r.mock, "GetBudget", reflect.TypeOf((*MockStore)(nil).GetBudget), ctx, id)
}

func (m *MockStore) GetBudgetByCategoryAndMonth(ctx context.Context, arg db.GetBudgetByCategoryAndMonthParams) (db.Budget, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBudgetByCategoryAndMonth", ctx, arg)
	return ret[0].(db.Budget), mockErr(ret[1])
}
func (r *MockStoreMockRecorder) GetBudgetByCategoryAndMonth(ctx, arg interface{}) *gomock.Call {
	return r.mock.ctrl.RecordCallWithMethodType(r.mock, "GetBudgetByCategoryAndMonth", reflect.TypeOf((*MockStore)(nil).GetBudgetByCategoryAndMonth), ctx, arg)
}

func (m *MockStore) ListBudgets(ctx context.Context, arg db.ListBudgetsParams) ([]db.Budget, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBudgets", ctx, arg)
	return ret[0].([]db.Budget), mockErr(ret[1])
}
func (r *MockStoreMockRecorder) ListBudgets(ctx, arg interface{}) *gomock.Call {
	return r.mock.ctrl.RecordCallWithMethodType(r.mock, "ListBudgets", reflect.TypeOf((*MockStore)(nil).ListBudgets), ctx, arg)
}

func (m *MockStore) UpdateBudget(ctx context.Context, arg db.UpdateBudgetParams) (db.Budget, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBudget", ctx, arg)
	return ret[0].(db.Budget), mockErr(ret[1])
}
func (r *MockStoreMockRecorder) UpdateBudget(ctx, arg interface{}) *gomock.Call {
	return r.mock.ctrl.RecordCallWithMethodType(r.mock, "UpdateBudget", reflect.TypeOf((*MockStore)(nil).UpdateBudget), ctx, arg)
}

func (m *MockStore) DeleteBudget(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBudget", ctx, id)
	return mockErr(ret[0])
}
func (r *MockStoreMockRecorder) DeleteBudget(ctx, id interface{}) *gomock.Call {
	return r.mock.ctrl.RecordCallWithMethodType(r.mock, "DeleteBudget", reflect.TypeOf((*MockStore)(nil).DeleteBudget), ctx, id)
}

// ── SavingsGoal ───────────────────────────────────────────────────────────────

func (m *MockStore) CreateSavingsGoal(ctx context.Context, arg db.CreateSavingsGoalParams) (db.SavingsGoal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSavingsGoal", ctx, arg)
	return ret[0].(db.SavingsGoal), mockErr(ret[1])
}
func (r *MockStoreMockRecorder) CreateSavingsGoal(ctx, arg interface{}) *gomock.Call {
	return r.mock.ctrl.RecordCallWithMethodType(r.mock, "CreateSavingsGoal", reflect.TypeOf((*MockStore)(nil).CreateSavingsGoal), ctx, arg)
}

func (m *MockStore) GetSavingsGoal(ctx context.Context, id int64) (db.SavingsGoal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSavingsGoal", ctx, id)
	return ret[0].(db.SavingsGoal), mockErr(ret[1])
}
func (r *MockStoreMockRecorder) GetSavingsGoal(ctx, id interface{}) *gomock.Call {
	return r.mock.ctrl.RecordCallWithMethodType(r.mock, "GetSavingsGoal", reflect.TypeOf((*MockStore)(nil).GetSavingsGoal), ctx, id)
}

func (m *MockStore) ListSavingsGoals(ctx context.Context, owner string) ([]db.SavingsGoal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSavingsGoals", ctx, owner)
	return ret[0].([]db.SavingsGoal), mockErr(ret[1])
}
func (r *MockStoreMockRecorder) ListSavingsGoals(ctx, owner interface{}) *gomock.Call {
	return r.mock.ctrl.RecordCallWithMethodType(r.mock, "ListSavingsGoals", reflect.TypeOf((*MockStore)(nil).ListSavingsGoals), ctx, owner)
}

func (m *MockStore) AddToSavingsGoal(ctx context.Context, arg db.AddToSavingsGoalParams) (db.SavingsGoal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddToSavingsGoal", ctx, arg)
	return ret[0].(db.SavingsGoal), mockErr(ret[1])
}
func (r *MockStoreMockRecorder) AddToSavingsGoal(ctx, arg interface{}) *gomock.Call {
	return r.mock.ctrl.RecordCallWithMethodType(r.mock, "AddToSavingsGoal", reflect.TypeOf((*MockStore)(nil).AddToSavingsGoal), ctx, arg)
}

func (m *MockStore) DeleteSavingsGoal(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSavingsGoal", ctx, id)
	return mockErr(ret[0])
}
func (r *MockStoreMockRecorder) DeleteSavingsGoal(ctx, id interface{}) *gomock.Call {
	return r.mock.ctrl.RecordCallWithMethodType(r.mock, "DeleteSavingsGoal", reflect.TypeOf((*MockStore)(nil).DeleteSavingsGoal), ctx, id)
}

// ── RecurringPayment ──────────────────────────────────────────────────────────

func (m *MockStore) CreateRecurringPayment(ctx context.Context, arg db.CreateRecurringPaymentParams) (db.RecurringPayment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRecurringPayment", ctx, arg)
	return ret[0].(db.RecurringPayment), mockErr(ret[1])
}
func (r *MockStoreMockRecorder) CreateRecurringPayment(ctx, arg interface{}) *gomock.Call {
	return r.mock.ctrl.RecordCallWithMethodType(r.mock, "CreateRecurringPayment", reflect.TypeOf((*MockStore)(nil).CreateRecurringPayment), ctx, arg)
}

func (m *MockStore) GetRecurringPayment(ctx context.Context, id int64) (db.RecurringPayment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRecurringPayment", ctx, id)
	return ret[0].(db.RecurringPayment), mockErr(ret[1])
}
func (r *MockStoreMockRecorder) GetRecurringPayment(ctx, id interface{}) *gomock.Call {
	return r.mock.ctrl.RecordCallWithMethodType(r.mock, "GetRecurringPayment", reflect.TypeOf((*MockStore)(nil).GetRecurringPayment), ctx, id)
}

func (m *MockStore) ListRecurringPayments(ctx context.Context, owner string) ([]db.RecurringPayment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRecurringPayments", ctx, owner)
	return ret[0].([]db.RecurringPayment), mockErr(ret[1])
}
func (r *MockStoreMockRecorder) ListRecurringPayments(ctx, owner interface{}) *gomock.Call {
	return r.mock.ctrl.RecordCallWithMethodType(r.mock, "ListRecurringPayments", reflect.TypeOf((*MockStore)(nil).ListRecurringPayments), ctx, owner)
}

func (m *MockStore) ListDueRecurringPayments(ctx context.Context, arg db.ListDueRecurringPaymentsParams) ([]db.RecurringPayment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDueRecurringPayments", ctx, arg)
	return ret[0].([]db.RecurringPayment), mockErr(ret[1])
}
func (r *MockStoreMockRecorder) ListDueRecurringPayments(ctx, arg interface{}) *gomock.Call {
	return r.mock.ctrl.RecordCallWithMethodType(r.mock, "ListDueRecurringPayments", reflect.TypeOf((*MockStore)(nil).ListDueRecurringPayments), ctx, arg)
}

func (m *MockStore) UpdateRecurringPaymentDueDate(ctx context.Context, arg db.UpdateRecurringPaymentDueDateParams) (db.RecurringPayment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRecurringPaymentDueDate", ctx, arg)
	return ret[0].(db.RecurringPayment), mockErr(ret[1])
}
func (r *MockStoreMockRecorder) UpdateRecurringPaymentDueDate(ctx, arg interface{}) *gomock.Call {
	return r.mock.ctrl.RecordCallWithMethodType(r.mock, "UpdateRecurringPaymentDueDate", reflect.TypeOf((*MockStore)(nil).UpdateRecurringPaymentDueDate), ctx, arg)
}

func (m *MockStore) DeleteRecurringPayment(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRecurringPayment", ctx, id)
	return mockErr(ret[0])
}
func (r *MockStoreMockRecorder) DeleteRecurringPayment(ctx, id interface{}) *gomock.Call {
	return r.mock.ctrl.RecordCallWithMethodType(r.mock, "DeleteRecurringPayment", reflect.TypeOf((*MockStore)(nil).DeleteRecurringPayment), ctx, id)
}

// ── TransferTx ────────────────────────────────────────────────────────────────

func (m *MockStore) TransferTx(ctx context.Context, arg db.TransferTxParams) (db.TransferTxResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TransferTx", ctx, arg)
	return ret[0].(db.TransferTxResult), mockErr(ret[1])
}
func (r *MockStoreMockRecorder) TransferTx(ctx, arg interface{}) *gomock.Call {
	return r.mock.ctrl.RecordCallWithMethodType(r.mock, "TransferTx", reflect.TypeOf((*MockStore)(nil).TransferTx), ctx, arg)
}

// ── helpers ───────────────────────────────────────────────────────────────────

func mockErr(v interface{}) error {
	if v == nil {
		return nil
	}
	return v.(error)
}

// Suppress unused import warning for time.
var _ = time.Now
